[project]
name = "libeq"
version = "0.3.0"
description = "Library for solving equilibrium in solution problems"
authors = [{name="Lorenzo Castellino", email="<castellino96@gmail.com>"},
           {name="Salvador Blasco", email="<salvador.blasco@uv.es>"}]
readme = "README.md"
packages = [{ include = "libeq", from = "src" }]
requires-python = ">= 3.10"
dependencies = [
 "numpy",
]

[project.scripts]
libeq = "..src"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.run.ini_options]
pythonpath = ["src"]

[tool.mypy]
mypy_path = "src"

[dependency-groups]
dev = [
    "numpy>=2.2.6",
    "pytest>=8.4.2",
]
